//! Self-printing scripts wrapping ANSI output.

/// POSIX sh: a quoted heredoc passes the raw escape bytes through untouched.
pub fn sh(ansi: &str) -> String {
    format!("#!/bin/sh\n# Generated by ansi-art\ncat <<'ANSI_ART_EOF'\n{ansi}ANSI_ART_EOF\n")
}

/// PowerShell 5.1+ and 7. The BOM is required for 5.1 to read the file as UTF-8,
/// and ESC is spliced in with `$e` because 5.1 lacks the "`e" escape.
pub fn ps1(ansi: &str) -> String {
    let mut body = String::with_capacity(ansi.len() + ansi.len() / 4);
    for ch in ansi.chars() {
        match ch {
            '\x1b' => body.push_str("$e"),
            '`' => body.push_str("``"),
            '$' => body.push_str("`$"),
            // Escaping quotes stops a line starting with `"@` from ending the here-string.
            '"' => body.push_str("`\""),
            ch => body.push(ch),
        }
    }
    let body = body.trim_end_matches('\n');
    format!(
        "\u{feff}# Generated by ansi-art\n\
         [Console]::OutputEncoding = [System.Text.Encoding]::UTF8\n\
         $e = [char]27\n\
         Write-Host @\"\n{body}\n\"@\n"
    )
}
